name: Build App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyqt6
      - name: Build macOS app
        run: pyinstaller main.spec
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: ImagineMusicReleaseMaster-macOS
          path: dist/ImagineMusicReleaseMaster

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyqt6
      - name: Build Windows exe
        run: pyinstaller main.spec
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: ImagineMusicReleaseMaster-Windows
          path: dist/ImagineMusicReleaseMaster
