name: Build Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install PyQt6
        
    - name: Build with PyInstaller
      run: |
        pyinstaller main.spec
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ImagineMusicReleaseMaster-${{ runner.os }}
        path: dist/ImagineMusicReleaseMaster/*
